name: E2E Tests

on:
  push:
    branches:
      - main 
jobs:
  test:
    runs-on: macos-13  # Run on the macOS Ventura for iOS testing

    steps:
      - uses: actions/checkout@v2
        name: Check out the code

      - name: Install dependencies
        run: npm ci  # Install dependencies using 'npm ci' for CI/CD

      - name: Run tests
        env:
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        run: npm test  # Run test script defined in package.json
